# Generated by Django 6.1.1 on 2026-09-18 20:52

import django.db.models.deletion
import rooms.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=rooms.models.generate_room_code, max_length=16, unique=True)),
                ('title', models.CharField(default='Arena Discussion Room', max_length=255)),
                ('host_name', models.CharField(default='Host', max_length=100)),
                ('max_participants', models.PositiveIntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peer_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_camera_off', models.BooleanField(default=False)),
                ('is_screen_sharing', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.room')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
