# Generated by Django 6.1.1 on 2026-09-19 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(default='System Design', max_length=100)),
                ('question_text', models.TextField()),
                ('current_speaker_peer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_turn_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished')], default='IDLE', max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=100)),
                ('peer_id', models.CharField(max_length=100)),
                ('transcript', models.TextField()),
                ('technical_score', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('feedback_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rooms.arenasession')),
            ],
        ),
    ]
